### PR TITLE
Support progress reporting and cancellation mid-way

### PR DESCRIPTION
**Pull request by LeonPoon**
In order to avoid touching lots of lines so as to keep the patch clean, things are copied out from the SaneSnapperObject struct to local variables before manipulation by existing code and copied back after.

Appreciate review. Thank you.

### CODE REVIEW

**Comment by LeonPoon** [comment]
I actually only just realised someone requested the same thing via #21 .

**Comment by manisandro** [comment]
Thanks for working on this! My low-level python is a bit rusty, but I wonder, would it be possible to do something async like [1]? It might be a bit more in line with how other APIs generally behave for such tasks.

[1] https://stackoverflow.com/a/36272211

**Comment by LeonPoon** [comment]
Python3 asyncio is relatively new to me so I took a bit of time today to do research.

Seems to me if we are to support it properly, we need to do this:

- spawn new pthread that will loop
- data struct to support cross-thread data exchange, with spin-locks/mutexes!
- make use of py3 async api https://docs.python.org/3/c-api/typeobj.html#async-object-structures (I am not sure if this's the right bits to use)
- some mechanisms to notify python space that there's progress to look at. This notification probably needs to work async too, so for good perf we might need a separate pthread just to marshal things, but this seems like a waste of context switches.
- some mechanism to avoid too many notification: squash progress updates together until python space is ready to look at it, after which any new progress result in new notification
- cancellation function and thread termination
- refactor existing py files to be compatible with all this.
- get the build system to work for both py2/3 because asyncio is new in 3.4. (We are talking about new py syntax so we can't just do a #ifdef)

Most of these are simple on its own but will take some time to implement the complete list. Going to take longer than the original work (took me a day for that)!

I will update when I have a go at it, meanwhile please send ideas if any - esp for managing the async notification part, if there are already existing solution. If there aren't then maybe it justify a new lib. Seems fun.

**Comment by manisandro** [comment]
Perhaps some other people can also express their opinion, from my part I was just wondering whether one could expose the api in a form like (abstractly written):

    job = start_scan_job(progressCallback = function(cur,tot), finishCallback=(result))

    job.cancel()

Whether that is specifically with the python3 async API is another question, though it seemed the closest at a first glance.

Again, this is just my opinion.

**Comment by manisandro** [comment]
Progress callbacks have been added in [1] and [2].

[1] https://github.com/python-pillow/Sane/commit/921151fb1be722db9731d7eaad16e334e0e685e4
[2] https://github.com/python-pillow/Sane/commit/5ef27fccd11319c26dd0ea04efaf5415aa6a948c

**Pull request closed without merging**
