### PR TITLE
support simple progress hook

### PR DESCRIPTION
**Pull request by WaferJay**
I think that ease of use is more important. So, I added a little code to hook current line and total lines.

```python
dev.snap(progress=lambda c, t: print(f'{c}/{t}'))
```

Have a nice day!

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks! Can `arr_snap` also be extended to take a progress hook?

**Comment by WaferJay** [comment]
Sure. I will commit it as soon as possible. How careless I am ...------------------ 原始邮件 ------------------
发件人: "Sandro Mani"<notifications@github.com>
发送时间: 2019年8月18日(星期天) 凌晨4:49
收件人: "python-pillow/Sane"<Sane@noreply.github.com>;
抄送: "WaferJay"<474346873@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [python-pillow/Sane] support simple progress hook (#54)



Thanks! Can arr_snap also be extended to take a progress hook?
 
&mdash;

**Comment by manisandro** [comment]
Great, thanks!

**Comment by WaferJay** [comment]
It is my pleasure. :-)

**Pull request merged**
